import Head from "next/head";
import MyApp from "./_app";
import Message from "../components/message";
import { useState, useEffect } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, query, orderBy } from "firebase/firestore";
import Link from "next/link";
import { doc, deleteDoc } from "firebase/firestore";
// import the button
import { AiFillEdit } from "react-icons/ai";
import { BsTrash2Fill } from "react-icons/bs";

export default function Home() {
  // state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getMessages = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const querySnapshot = onSnapshot(q, (querySnapshot) =>
      setAllPosts(
        querySnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }))
      )
    );
    return querySnapshot;
  };

  async function deletePost(id) {
    const docRef = doc(db, "posts", id);
    await deleteDoc(docRef);
  }

  useEffect(() => {
    getMessages();
  }, []);

  // the post component

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white ">
        <h1 className="text-4xl text-center my-4">
          see what other people saying
        </h1>
        {allPosts.map((post) => (
          <Message key={post.id} post={post}>
            {/* here must be the comment section */}
            <div className="w-full flex justify-start items-center gap-8 text-sm ml-4 ">
              <button
                onClick={() => deletePost(post.id)}
                className="text-red-700 flex gap-2"
              >
                <BsTrash2Fill /> Delete
              </button>
              <Link href={{ pathname: "/post", query: post }}>
                <button className="text-teal-700 flex gap-2">
                  <AiFillEdit /> Edit
                </button>
              </Link>
              <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
                <button className="text-xl border border-gray-500 p-1 rounded hover:bg-slate-600 hover:text-white transition-all">
                  {post.comments?.length ? post.comments?.length : 0} Comments
                </button>
              </Link>
            </div>
          </Message>
        ))}
      </main>
    </div>
  );
}
